[package]
name = "checkers-perft"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "4.5.42", features = ["derive"] }

[profile.release]
opt-level = 3
lto = true
